services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant-storage/:/qdrant/storage:z
    networks:
      - app-network

  information-vector-db-service:
    build: information-vector-db-service
    ports:
      - "3000:3000"
    volumes:
      - ./information-vector-db-service:/app/
    environment:
      - QDRANT_URL=http://qdrant:6333
      - NOMIC_API_KEY=${NOMIC_API_KEY}
    depends_on:
      - qdrant
    networks:
      - app-network

  information:
    build: informationService
    volumes:
      - ./informationService:/app/
  vectorial:
    build: vectorialDbService
    volumes:
      - ./vectorialDbService:/app/
  rabbitmq:
    image: rabbitmq