services:
  information:
    build: informationService
    volumes:
      - ./informationService:/app/
  vectorial:
    build: vectorialDbService
    volumes:
      - ./vectorialDbService:/app/
  rabbitmq:
    image: rabbitmq