services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant-storage/:/qdrant/storage:z

  information-vector-db-service:
    build: information-vector-db-service
    volumes:
      - ./information-vector-db-service:/app/

  information:
    build: information-vector-db-service
    env_file:
      - information-vector-db-service/.env
    #volumes:
    #  - ./information-vector-db-service:/app/
  test:
    build: test
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672" 


volumes:
  postgres_data: