services:
  information:
    build: information-vector-db-service
    #volumes:
    #  - ./information-vector-db-service:/app/
  test:
    build: test
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq